# Generated by Django 6.0.4 on 2026-05-10 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=120)),
                ('provider_type', models.CharField(choices=[('openai', 'openai'), ('ollama', 'ollama'), ('openai_compatible', 'openai_compatible'), ('custom', 'custom')], max_length=32)),
                ('base_url', models.URLField(blank=True, max_length=500)),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('model_name', models.CharField(max_length=160)),
                ('temperature', models.FloatField(default=0.85)),
                ('max_tokens', models.PositiveIntegerField(default=5000)),
                ('timeout_ms', models.PositiveIntegerField(default=90000)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_provider_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_provider_configs',
                'ordering': ['-is_default', 'provider_name'],
                'indexes': [models.Index(fields=['owner', 'provider_type'], name='ai_provider_owner_i_178681_idx'), models.Index(fields=['owner', 'is_default'], name='ai_provider_owner_i_35b355_idx')],
            },
        ),
    ]
